#!/usr/bin/env ruby
# encoding: utf-8
require 'yaml'
require_relative 'exportsvg.rb'

def isAnterior?(oldFile, newFile)
  File.mtime(oldFile) < File.mtime(newFile)
end

configurationFile = ARGV[0].to_s

# charger la configuration
configuration = YAML.load(File.read(configurationFile))['simplesvgexport']

# pour chaque fichier source/destination
Dir.chdir(File.dirname(configurationFile)) do
  configuration.each do |options|
    
    begin
      next if isAnterior? options['in'], options['out']
    rescue
    end

    exportsvg options['in'], options['out'] if File.readable?(options['in'])
  end
end
