#!/usr/bin/env ruby
# encoding: utf-8
require 'yaml'
require_relative 'exportsvg.rb'

configurationFile = ARGV[0].to_s

# charger la configuration
configuration = YAML.load(File.read(configurationFile))['simplesvgexport']

# pour chaque fichier source/destination
Dir.chdir(File.dirname(configurationFile)) do
  configuration.each do |options|
    exportsvg options['in'], options['out'] if File.readable?(options['in'])
  end
end
